### PR TITLE
Consistent double quotes

### PR DESCRIPTION
**Pull request by imteekay**
Add double quotes for the imports in the test file to make it consistent across the codebase.

(let me know if you prefer double or single quotes)

### CODE REVIEW

**Comment by LauraBeatris** [comment]
Consistent is always important!! Thanks for catching this 

``lint-staged`` isn't linting the test files. The source pattern is only targeting the files inside the ``src`` directory 

https://github.com/LauraBeatris/use-platform/blob/3de7852af7cd6f1003839860af3982fe91bf8823/package.json#L17

Can you also update the lint script to target the test files? Thanks

**Comment by leandrotk** [comment]
Adjusted the eslint config in the package.json and pass the lint in the test file to fix some inconsistencies.

**Comment by imteekay** [comment]
Adjusted the eslint config in the package.json and pass the lint in the test file to fix some inconsistencies, @LauraBeatris.

**Comment by LauraBeatris** [comment]
Awesome! Merged 👍

**Pull request merged**
